In [1]:
# Standard Imports
import numpy as np, pandas as pd, random, json, time, os

# Plotly Imports
import plotly.graph_objects as go
import plotly.express as px

# Dash Imports
import dash
from dash import dcc
from dash import html
from dash.dependencies import Input, Output

# Additional Imports
# import STUFF



# Load CSS sheet for style information
external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

# Define the Web-App Object and set to variable "server"
app = dash.Dash(__name__, external_stylesheets=external_stylesheets)
server = app.server

# Suppres some output
app.config.suppress_callback_exceptions = True


#################################################
################# Layout ########################
#################################################

app.layout = html.Div([
    #h1 = level 1 header, etc...#
    html.H1(children='Super Simple Dash App!'),
    html.H2(children='This is an example of a dash app with an interactive dashboard.'),
    
    html.H6("Change below to make a new figure:"),
    
    html.Div([
           "     Number of points, N=: ",
           dcc.Input(id='my-input', value=10, type='number', debounce = True)
    ], style={'width':600}),

    html.Div([
		"     Size of Noise, s=: ",
		dcc.Input(id='my-input2', value=1, type='number', debounce = True)
	]),
    
    
    html.Br(),
    
    
    html.Div([
        html.Div([
            dcc.Graph(id='figure-output')], 
            style={'width': '49%', 'display': 'inline-block', 'vertical-align': 'middle'}),

        html.Div([dcc.Graph(id='figure-output2')], 
            style={'width': '49%', 'display': 'inline-block', 'vertical-align': 'middle'})
    ]),

])

#####################
# Plot one          #
#####################
@app.callback(
    Output('figure-output2', 'figure'),
    Input('my-input', 'value'))    
def make_plot(N):
        
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=np.arange(N), y=3*np.random.rand(N),
                    mode='lines',
                    name='MORE RANDOM DATA'))
                    
    fig.update_layout(title="Model Output")
    
    return fig  
    




#####################
# Plot two          #
#####################
@app.callback(
    Output('figure-output', 'figure'),
    Input('my-input', 'value'),
    Input('my-input2', 'value'))    
def make_plot(N,s=1):
        
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=np.arange(N), y=s*np.random.rand(N),
                    mode='lines',
                    name='Random Data'))
                    
    fig.update_layout(title="Model Output")
    
    return fig    




    
# -------------------------- MAIN ---------------------------- #


# This is the code that gets run when we call this file from the terminal
# The port number can be changed to fit your particular needs
if __name__ == '__main__':
    app.run_server(host='0.0.0.0', port=8080, debug=True, use_reloader=False)

Dash is running on http://0.0.0.0:8080/

 * Serving Flask app '__main__'
 * Debug mode: on

In [13]:
df = pd.read_csv("CSV/nsf23300-tab001-007.csv", encoding = "cp1252")
#df['TotRank'] = df['Total'].rank()
dftrans=df.T
dftrans[0:25]

,0,1,2,3,4,5,6,7,8,9,...,122,123,124,125,126,127,128,129,130,131
Field and citizenship status,All doctorate recipientsa,Life sciences,Agricultural sciences and natural resources,Biological and biomedical sciences,Health sciences,Physical sciences and earth sciences,Chemistry,"Geosciences, atmospheric sciences, and ocean s...",Physics and astronomy,Mathematics and computer sciences,...,Other education,Humanities and arts,Foreign languages and literature,History,Letters,Other humanities and arts,Other,Business management and administration,Communication,Non-science and engineering fields nec
2011,48909,11535,1206,8152,2177,5271,2432,852,1987,3273,...,53,767,180,131,157,299,786,477,132,177
2012,50943,11964,1255,8322,2387,5419,2416,941,2062,3496,...,31,761,160,136,141,324,834,542,107,185
2013,52703,12207,1324,8354,2529,5584,2484,989,2111,3660,...,31,779,179,134,150,316,945,600,133,212
2014,53986,12484,1338,8868,2278,5910,2673,1098,2139,3862,...,36,731,142,147,140,302,905,589,137,179
2015,54886,12493,1434,8783,2276,5916,2666,1057,2193,3818,...,33,713,151,131,122,309,867,546,137,184
2016,54809,12539,1379,8863,2297,6251,2703,1227,2321,3954,...,69,712,164,142,126,280,890,553,160,177
2017,54552,12554,1493,8566,2495,6082,2699,1169,2214,3842,...,42,692,159,125,122,286,940,588,122,230
2018,55080,12754,1442,8782,2530,6330,2807,1185,2338,4022,...,43,739,181,112,139,307,1028,642,165,221
2019,55609,12748,1488,8678,2582,6579,2939,1272,2368,4230,...,77,826,202,130,149,345,1106,689,163,254
2020,55224,12549,1470,8410,2669,6241,2761,1241,2239,4387,...,49,742,185,120,132,305,1075,658,153,264
2021,52250,11814,1334,8149,2331,5757,2555,1064,2138,4373,...,54,727,117,128,172,310,1142,683,140,319
% change 2011–21,6.8,2.4,10.6,0.0,7.1,9.2,5.1,24.9,7.6,33.6,...,1.9,-5.2,-35.0,-2.3,9.6,3.7,45.3,43.2,6.1,80.2