In [2]:
# Standard Imports
import numpy as np, pandas as pd, random, json, time, os

# Plotly Imports
import plotly.graph_objects as go
import plotly.express as px

# Dash Imports
import dash
from dash import dcc
from dash import html
from dash.dependencies import Input, Output

# Additional Imports
# import STUFF



# Load CSS sheet for style information
external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

# Define the Web-App Object and set to variable "server"
app = dash.Dash(__name__, external_stylesheets=external_stylesheets)
server = app.server

# Suppres some output
app.config.suppress_callback_exceptions = True


#################################################
################# Layout ########################
#################################################

app.layout = html.Div([
    #h1 = level 1 header, etc...#
    html.H1(children='Super Simple Dash App!'),
    html.H2(children='This is an example of a dash app with an interactive dashboard.'),
    
    html.H6("Change below to make a new figure:"),
    
    html.Div([
           "     Number of points, N=: ",
           dcc.Input(id='my-input', value=10, type='number', debounce = True)
    ], style={'width':600}),

    html.Div([
		"     Size of Noise, s=: ",
		dcc.Input(id='my-input2', value=1, type='number', debounce = True)
	]),
    
    
    html.Br(),
    
    
    html.Div([
        html.Div([
            dcc.Graph(id='figure-output')], 
            style={'width': '49%', 'display': 'inline-block', 'vertical-align': 'middle'}),

        html.Div([dcc.Graph(id='figure-output2')], 
            style={'width': '49%', 'display': 'inline-block', 'vertical-align': 'middle'})
    ]),

])

#####################
# Plot one          #
#####################
@app.callback(
    Output('figure-output2', 'figure'),
    Input('my-input', 'value'))    
def make_plot(N):
        
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=np.arange(N), y=3*np.random.rand(N),
                    mode='lines',
                    name='MORE RANDOM DATA'))
                    
    fig.update_layout(title="Model Output")
    
    return fig  
    




#####################
# Plot two          #
#####################
@app.callback(
    Output('figure-output', 'figure'),
    Input('my-input', 'value'),
    Input('my-input2', 'value'))    
def make_plot(N,s=1):
        
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=np.arange(N), y=s*np.random.rand(N),
                    mode='lines',
                    name='Random Data'))
                    
    fig.update_layout(title="Model Output")
    
    return fig    




    
# -------------------------- MAIN ---------------------------- #


# This is the code that gets run when we call this file from the terminal
# The port number can be changed to fit your particular needs
if __name__ == '__main__':
    app.run_server(host='0.0.0.0', port=8080, debug=True, use_reloader=False)

Dash is running on http://0.0.0.0:8080/

 * Serving Flask app '__main__'
 * Debug mode: on

In [4]:
df = pd.read_csv("CSV/nsf23300-tab007-006.csv")
df

,State or location,Rank,Total,Male,Female,Tot Sci Eng,Male Sci Eng,Female Sci Eng,Tot Non Sci,Male Non Sci,Female Non Sci
0,California,1,"5,892","3,267","2,623","4,959","2,848","2,109",933,419,514
1,Texas,2,"4,118","2,213","1,904","3,155","1,803","1,352",963,410,552
2,New York,3,"3,871","2,030","1,840","2,975","1,653","1,321",896,377,519
3,Massachusetts,4,"2,652","1,501","1,151","2,180","1,273",907,472,228,244
4,Pennsylvania,5,"2,434","1,288","1,145","1,897","1,062",834,537,226,311
5,Florida,6,"2,339","1,219","1,120","1,784","1,008",776,555,211,344
6,Illinois,7,"2,310","1,304","1,005","1,847","1,056",790,463,248,215
7,Ohio,8,"1,878",963,914,"1,428",783,644,450,180,270
8,Michigan,9,"1,790",971,819,"1,446",838,608,344,133,211
9,North Carolina,10,"1,724",917,807,"1,407",784,623,317,133,184
10,Indiana,11,"1,556",882,674,"1,250",739,511,306,143,163
11,Virginia,12,"1,518",802,716,"1,147",660,487,371,142,229
12,Minnesota,13,"1,499",648,851,"1,075",500,575,424,148,276
13,Georgia,14,"1,451",776,675,"1,217",686,531,234,90,144
14,Maryland,15,"1,173",586,586,"1,004",527,477,169,59,109
15,Colorado,16,"1,024",558,466,828,479,349,196,79,117
16,New Jersey,17,950,525,425,736,437,299,214,88,126
17,Wisconsin,18,940,521,419,759,449,310,181,72,109
18,Arizona,19,935,535,399,734,444,289,201,91,110
19,Washington,20,910,498,412,780,443,337,130,55,75
20,Missouri,21,905,538,367,697,413,284,208,125,83
21,Tennessee,22,880,454,426,669,370,299,211,84,127
22,Connecticut,23,731,413,317,603,340,262,128,73,55
23,Alabama,24,640,325,315,467,259,208,173,66,107
24,Iowa,25,618,362,256,517,318,199,101,44,57
25,Louisiana,26,586,313,273,436,248,188,150,65,85
26,Oregon,27,552,280,271,453,233,219,99,47,52
27,District of Columbia,28,535,252,283,376,173,203,159,79,80
28,Utah,29,502,295,207,402,251,151,100,44,56
29,Kentucky,30,484,265,219,336,193,143,148,72,76
30,Oklahoma,30,484,262,222,346,204,142,138,58,80
31,South Carolina,32,476,256,220,383,222,161,93,34,59
32,Kansas,33,466,258,208,361,206,155,105,52,53
33,Mississippi,34,409,194,215,276,140,136,133,54,79
34,Nebraska,35,329,165,164,264,141,123,65,24,41
35,New Mexico,36,280,151,129,214,127,87,66,24,42
36,Arkansas,37,275,146,129,198,117,81,77,29,48
37,Rhode Island,38,260,142,118,210,116,94,50,26,24
38,Nevada,39,240,119,120,187,99,88,53,20,32
39,West Virginia,40,215,122,93,164,97,67,51,25,26
40,Delaware,41,212,116,96,185,106,79,27,10,17
41,North Dakota,42,175,90,85,123,69,54,52,21,31
42,New Hampshire,43,159,90,69,144,86,58,15,4,11
43,Idaho,44,136,80,56,115,72,43,21,8,13
44,Hawaii,45,133,55,78,95,39,56,38,16,22
45,South Dakota,46,122,77,45,108,66,42,14,11,3
46,Montana,47,113,59,54,92,49,43,21,10,11
47,Puerto Rico,48,109,47,62,94,40,54,15,7,8
48,Wyoming,49,84,65,19,76,60,16,8,5,3
49,Maine,50,70,31,39,58,28,30,12,3,9
50,Vermont,51,64,35,29,60,34,26,4,1,3
51,Alaska,52,42,21,21,39,20,19,3,1,2